[project]
name = 'myfolder'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.progressive-trust-lending]
path = 'contracts/progressive-trust-lending.clar'
clarity_version = 3
epoch = 3.0



[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
